### ISSUE TITLE
Improve area selector

### ISSUE THREAD

**Issue by SeaDve** [SeaDve/Kooha#192]
- [ ] #274
- [x] Improve styling (https://gitlab.gnome.org/Teams/Design/os-mockups/-/issues/175)
- [x] Make cursor on first drag more consistent with gnome-shell
- [x] Make the window resizable and properly set paintable rect

**Comment by cypherbits** [comment]
Sorry, just here to say I liked the old way of selecting area (until v2.1 included ) since it allowed more perfect pixel selection (since a window is always smaller you don't have that control).
Thanks for your work.

**Comment by SeaDve** [comment]
> Sorry, just here to say I liked the old way of selecting area (until v2.1 included ) since it allowed more perfect pixel selection (since a window is always smaller you don't have that control). Thanks for your work.

That's unfortunately a disadvantage, but moving to this kind of area selector fixed a bunch of other critical issues that I believe makes that trade off worth it.

**Comment by mcmxcdev** [comment]
Thought I would also add my 2 cents to this: 
I mostly need to record an area of the screen rather than a whole window (for showing frontend UI changes to the team) and I absolutely love how https://github.com/phw/peek is doing it. I need to see while recording where the boundaries of the area are, otherwise I am most likely ending up doing actions outside the recorded area. 

The tool is lacking in maintenance unfortunately so that's why I am looking at Kooha to replace it eventually.

**Comment by SeaDve** [comment]
> Thought I would also add my 2 cents to this:
I mostly need to record an area of the screen rather than a whole window (for showing frontend UI changes to the team) and I absolutely love how https://github.com/phw/peek is doing it. I need to see while recording where the boundaries of the area are, otherwise I am most likely ending up doing actions outside the recorded area.

It is unfortunately not practically possible currently because of restrictive Wayland APIs. This section on peek also shares the same issues with Kooha: https://github.com/phw/peek?tab=readme-ov-file#why-no-native-wayland-support
